---
    - ec2_vpc:
        state: present
        vpc_id: vpc-test123
        cidr_block: 10.0.0.0/16
        resource_tags: { "Environment":"DevOps" }
         subnets:
          - cidr: 10.0.1.0/24
            az: us-east-2c
            resource_tags: { "Environment":"DevOps", "Tier" : "Web" }
          - cidr: 10.0.2.0/24
            az: us-east-2b
            resource_tags: { "Environment":"DevOps", "Tier" : "App" }
          - cidr: 10.0.3.0/24
            az: us-east-2a
            resource_tags: { "Environment":"DevOps", "Tier" : "DB" }
        internet_gateway: True
        route_tables:
          - subnets:
              - 10.0.2.0/24
              - 10.0.3.0/24
            routes:
              - dest: 0.0.0.0/0
                gw: igw
          - subnets:
              - 10.0.1.0/24
            routes:
              - dest: 0.0.0.0/0
                gw: igw
        region: {{ region }}
      register: vpc